apiVersion : apps/v1
kind: Deployment
metadata:
  name: "82209856"
  namespace: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "82209856"
  template:
    metadata:
      labels:
        app: "82209856"
    spec:
      tolerations:
      - key: taint-test
        operator: Equal
        value: value
        effect: NoSchedule
      containers:
        - name: "82209856"
          image: cepgbaseacr.azurecr.io/troubleshooting:latest
          resources:
            limits:
              memory: 800Mi
              cpu: 1
